#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Translation\Command\XliffLintCommand;

$application = new Application();
$application->add(new XliffLintCommand);
$application->setDefaultCommand('lint:xliff', true);
$application->run();
